-d /home/kali/apka/3Way/3Way/impl/gwsynthesis/3Way.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /home/kali/apka/3Way/constr/pins.cst
-cfg /home/kali/apka/3Way/3Way/impl/pnr/device.cfg
-sdc /home/kali/apka/3Way/constr/clocks.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
